##Reto modulo 1 Pamela Hernández

In [2]:
import pandas as pd
from sklearn.linear_model import Ridge
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [13]:
EmpleadosAttrition = pd.read_csv("empleadosRETO.csv")

In [14]:
#Borrar columnas no necesarias
EmpleadosAttrition = EmpleadosAttrition.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'], axis=1)

In [15]:
EmpleadosAttrition.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   DistanceFromHome          400 non-null    object
 4   Education                 400 non-null    int64
 5   EducationField            400 non-null    object
 6   EnvironmentSatisfaction   400 non-null    int64
 7   Gender                    400 non-null    object
 8   JobInvolvement            400 non-null    int64
 9   JobLevel                  400 non-null    int64
 10  JobRole                   400 non-null    object
 11  JobSatisfaction           400 non-null    int64
 12  MaritalStatus             395 non-null    object
 13  MonthlyIncome             400 non-null    int64
 14  NumCompaniesWorked        400 non-null    int64
 15  HiringDate                400 non-null    object
 16  OverTime                  400 non-null    object
 17  PercentSalaryHike         400 non-null    int64
 18  PerformanceRating         400 non-null    int64
 19  RelationshipSatisfaction  400 non-null    int64
 20  TotalWorkingYears         400 non-null    int64
 21  TrainingTimesLastYear     400 non-null    int64
 22  WorkLifeBalance           400 non-null    int64
 23  YearsInCurrentRole        400 non-null    int64
 24  YearsSinceLastPromotion   400 non-null    int64
 25  Attrition                 400 non-null    object
dtypes: int64(16), object(10)
memory usage: 81.4+ KB

In [17]:
# Convertir a formato de fecha la columna HirindDate porque en la visualización que dimos antes 
# en el archivo se vio que tienen diefrente formato
EmpleadosAttrition["HiringDate"] = pd.to_datetime(EmpleadosAttrition["HiringDate"], errors="coerce")

In [19]:
#se crea la nueva columna y con el datetimeIndex queda directa como tipo entero
EmpleadosAttrition['Year'] = pd.DatetimeIndex(EmpleadosAttrition['HiringDate']).year

In [20]:
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,22,4,3,32,1,2,4,1,No,2013.0
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,20,4,4,7,0,3,2,0,No,2015.0
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,13,3,2,1,3,3,0,1,Yes,2017.0

In [22]:
#Columna de años en la compañía hasta el 2018
EmpleadosAttrition['YearsAtCompany'] = 2018 - EmpleadosAttrition['Year']
EmpleadosAttrition.head(3)

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,4,3,32,1,2,4,1,No,2013.0,5.0
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,4,7,0,3,2,0,No,2015.0,3.0
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,...,3,2,1,3,3,0,1,Yes,2017.0,1.0

In [23]:
#Renombrar columna DistanceFromHome
EmpleadosAttrition = EmpleadosAttrition.rename(columns={'DistanceFromHome':'DistanceFromHome_km'})
EmpleadosAttrition.head(2)

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,4,3,32,1,2,4,1,No,2013.0,5.0
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,4,7,0,3,2,0,No,2015.0,3.0

In [ ]:
#Crear columna DistanceFromHome solo numero entero
#str[0] porque se dividio en 2 y el que queremos tiene indice 0
EmpleadosAttrition['DistanceFromHome'] = EmpleadosAttrition['DistanceFromHome_km'].str.split(pat=' ').str[0].astype(int)
EmpleadosAttrition.head(2)

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,...,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,...,3,32,1,2,4,1,No,2013.0,5.0,1
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,...,4,7,0,3,2,0,No,2015.0,3.0,6

In [26]:
#Borrat las columnas que ya no se ocupan
EmpleadosAttrition = EmpleadosAttrition.drop(['Year','HiringDate','DistanceFromHome_km'], axis=1)

In [27]:
#df de sueldo promedio por departamento
SueldoPromedio = EmpleadosAttrition.groupby(['Department'])[['MonthlyIncome']].mean()
SueldoPromedio

                        MonthlyIncome
Department
Human Resources           6239.888889
Research & Development    6804.149813
Sales                     7188.250000

In [28]:
#Escalar variable MonthlyIncome con valor entre 0 y 1
EmpleadosAttrition['MonthlyIncome'] = (EmpleadosAttrition['MonthlyIncome'] - min(EmpleadosAttrition['MonthlyIncome']))/(max(EmpleadosAttrition['MonthlyIncome'])-min(EmpleadosAttrition['MonthlyIncome']))
EmpleadosAttrition['MonthlyIncome'].describe()

count    400.000000
mean       0.311196
std        0.258308
min        0.000000
25%        0.106939
50%        0.222711
75%        0.462745
max        1.000000
Name: MonthlyIncome, dtype: float64

In [34]:
EmpleadosAttrition_ = EmpleadosAttrition.copy()

##Convertir variables categóricas a numericas

In [ ]:
#codificar la columna BusinessTravel con Ho porque son mas de 2 opciones
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['BusinessTravel']])

# Crear DataFrame con nombres de columnas 
BusinessTravelHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['BusinessTravel']))

In [40]:
BusinessTravelHO.head(2)

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,BusinessTravel_nan
0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0

In [42]:
#codificar la columna Department con Ho porque son mas de 2 opciones
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['Department']])

# Crear DataFrame con nombres de columnas
DepartmentHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Department']))

In [43]:
DepartmentHO.head(2)

,Department_Human Resources,Department_Research & Development,Department_Sales
0,0.0,1.0,0.0
1,0.0,1.0,0.0

In [44]:
#codificar la columna eduaction con Ho porque son mas de 2 opciones
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['EducationField']])

# Crear DataFrame con nombres de columnas
EducationFieldHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['EducationField']))

In [45]:
EducationFieldHO.head(2)

,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree
0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0

In [47]:
#codificar la columna Gender con Ho porque son 2 opciones y las queremos en numero
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['Gender']])

# Crear DataFrame con nombres de columnas
GenderHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Gender']))

In [48]:
GenderHO.head(2)

   Gender_Female  Gender_Male
0            0.0          1.0
1            0.0          1.0

In [49]:
#codificar la columna JobRole con Ho 
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['JobRole']])

# Crear DataFrame con nombres de columnas
JobRoleHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['JobRole']))

In [51]:
JobRoleHO.columns

Index(['JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative'],
      dtype='object')

In [52]:
#codificar la columna MaritalStatus con Ho 
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['MaritalStatus']])

# Crear DataFrame con nombres de columnas
MaritalStatusHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['MaritalStatus']))

In [53]:
MaritalStatusHO.columns

Index(['MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'MaritalStatus_nan'],
      dtype='object')

In [54]:
#codificar la columna Attrition con Ho 
encoder = OneHotEncoder(sparse_output=False) #para que el resultado sea un array normal y no una matriz dispersa

# Ajustar y transformar
encoded = encoder.fit_transform(EmpleadosAttrition[['Attrition']])

# Crear DataFrame con nombres de columnas
AttritionHO = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Attrition']))

In [55]:
AttritionHO.columns

Index(['Attrition_No', 'Attrition_Yes'], dtype='object')

##Borro las columnas que categoricas y concateno las numericas creadas

In [ ]:
#Borrar columnas categóricas
EmpleadosAttrition = EmpleadosAttrition.drop(['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Attrition'], axis=1)

In [57]:
#Concateno los df de las variables numericas HO
EmpleadosAttrition = pd.concat([BusinessTravelHO,DepartmentHO,EducationFieldHO,GenderHO,JobRoleHO,MaritalStatusHO,AttritionHO], axis=1)

In [59]:
EmpleadosAttrition.columns

Index(['BusinessTravel_Non-Travel', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'BusinessTravel_nan',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Human Resources',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Female', 'Gender_Male',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single', 'MaritalStatus_nan',
       'Attrition_No', 'Attrition_Yes'],
      dtype='object')

##Correlaciones y PCA

In [61]:
#Como atrition solo fueron 2 variables borramos una, ya que la otra indica ambos valores y la renombramos
EmpleadosAttrition = EmpleadosAttrition.drop(['Attrition_Yes'], axis=1)
EmpleadosAttrition = EmpleadosAttrition.rename(columns={'Attrition_No':'Attrition'})

In [62]:
#Correlaciones
# Lista de variables
variables = [
    'BusinessTravel_Non-Travel', 'BusinessTravel_Travel_Frequently',
    'BusinessTravel_Travel_Rarely', 'BusinessTravel_nan',
    'Department_Human Resources', 'Department_Research & Development',
    'Department_Sales', 'EducationField_Human Resources',
    'EducationField_Life Sciences', 'EducationField_Marketing',
    'EducationField_Medical', 'EducationField_Other',
    'EducationField_Technical Degree', 'Gender_Female', 'Gender_Male',
    'JobRole_Healthcare Representative', 'JobRole_Human Resources',
    'JobRole_Laboratory Technician', 'JobRole_Manager',
    'JobRole_Manufacturing Director', 'JobRole_Research Director',
    'JobRole_Research Scientist', 'JobRole_Sales Executive',
    'JobRole_Sales Representative', 'MaritalStatus_Divorced',
    'MaritalStatus_Married', 'MaritalStatus_Single', 'MaritalStatus_nan',
    'Attrition'
]

# Calcular correlación respecto a Attrition_No
correlaciones = EmpleadosAttrition[variables].corr()["Attrition"]

In [63]:
correlaciones

BusinessTravel_Non-Travel            0.100698
BusinessTravel_Travel_Frequently    -0.035387
BusinessTravel_Travel_Rarely        -0.042755
BusinessTravel_nan                   0.044677
Department_Human Resources          -0.023389
Department_Research & Development    0.072269
Department_Sales                    -0.066116
EducationField_Human Resources      -0.043404
EducationField_Life Sciences         0.027457
EducationField_Marketing            -0.016768
EducationField_Medical               0.054144
EducationField_Other                 0.004275
EducationField_Technical Degree     -0.129104
Gender_Female                       -0.028839
Gender_Male                          0.028839
JobRole_Healthcare Representative    0.103274
JobRole_Human Resources             -0.032714
JobRole_Laboratory Technician       -0.125264
JobRole_Manager                      0.089885
JobRole_Manufacturing Director       0.042404
JobRole_Research Director            0.116263
JobRole_Research Scientist          -0.007977
JobRole_Sales Executive              0.003115
JobRole_Sales Representative        -0.191294
MaritalStatus_Divorced               0.107869
MaritalStatus_Married                0.094734
MaritalStatus_Single                -0.205849
MaritalStatus_nan                   -0.010609
Attrition                            1.000000
Name: Attrition, dtype: float64

In [64]:
#Correlaciones mayor o igual a 0.1
EmpleadosAttritionFinal = EmpleadosAttrition[['Attrition','BusinessTravel_Non-Travel','EducationField_Technical Degree','JobRole_Healthcare Representative',
                                              'JobRole_Laboratory Technician','JobRole_Research Director','JobRole_Sales Representative',
                                              'MaritalStatus_Divorced','MaritalStatus_Single']]

In [65]:
EmpleadosAttritionFinal.columns

Index(['Attrition', 'BusinessTravel_Non-Travel',
       'EducationField_Technical Degree', 'JobRole_Healthcare Representative',
       'JobRole_Laboratory Technician', 'JobRole_Research Director',
       'JobRole_Sales Representative', 'MaritalStatus_Divorced',
       'MaritalStatus_Single'],
      dtype='object')

In [66]:
#PCA
from sklearn.decomposition import PCA

pca = PCA() #instancia PCA se le pone un numero de acuerdo con las variables principales que se requieran, si no es nada son todas
pca.fit(EmpleadosAttritionFinal) #datos componentes principales
print(pca.components_)

[[-2.76943396e-01 -3.81908943e-02  9.94895063e-03 -3.82320638e-02
  -6.23710496e-02 -1.86169562e-02  1.08885520e-01 -6.10212336e-01
   7.29267611e-01]
 [-5.58168230e-01  4.02241101e-02  1.96875984e-02 -2.27939328e-01
   7.32016183e-01 -2.00411255e-01  3.11751347e-02  2.37931451e-01
   2.98443031e-02]
 [-2.67647665e-01  1.46107564e-02  1.84535288e-02  4.94800776e-02
  -4.47769877e-01 -4.66713373e-03  1.65692502e-01  7.12939844e-01
   4.34862704e-01]
 [ 6.07282862e-01  4.15379215e-01 -1.96803591e-01 -7.00789013e-02
   3.59133603e-01  5.01747172e-02 -1.42534511e-01  2.00353748e-01
   4.72305800e-01]
 [ 2.76222231e-02  2.82281336e-02  3.88000891e-02  7.83982490e-01
   9.85582778e-02 -6.06305676e-01 -5.09882998e-02 -5.45084424e-03
   4.85424417e-02]
 [-1.86969012e-01  8.81112135e-01  1.15152626e-01 -9.55126650e-02
  -2.18056266e-01 -1.49709553e-01  1.87580327e-01 -1.43117694e-01
  -2.01669679e-01]
 [-3.03448108e-01  2.12431068e-01 -3.49092953e-02  5.07456876e-01
   1.19771787e-01  6.96677424e-01 -3.23036489e-01  1.81641735e-03
   7.48859591e-04]
 [ 2.07882595e-01 -4.01040378e-02  6.51518271e-01  1.70453914e-01
   2.29230071e-01  2.57732039e-01  6.16793193e-01  3.03106346e-02
   3.63468308e-02]
 [ 1.75074080e-02  1.67151519e-02  7.21097039e-01 -1.70012969e-01
  -8.14455513e-02 -1.23063780e-01 -6.45623234e-01  3.42091320e-02
   1.03687260e-01]]

In [67]:
#Evaluación de componentes obtenidos
print(pca.explained_variance_)

[0.27341381 0.16517507 0.12796267 0.12169641 0.09559116 0.08140091
 0.06988362 0.05263912 0.04539511]

Eso significa que, de la suma de esa lista, el primer componente explica 27.34 puntos de la varianza y el segundo 16.51. Es decir, que información de este conjunto de datos puede ser obtenida con cada componente, entre menor puntos no contiene mucha información.

In [68]:
#Para pasar a porcentajes con..
print(pca.explained_variance_ratio_)

[0.26463894 0.15987398 0.12385587 0.11779072 0.09252329 0.07878845
 0.06764079 0.05094974 0.04393822]

In [69]:
#Formar nuevas variables
EmpleadosAttritionPCA = pca.transform(EmpleadosAttritionFinal)

In [70]:
EmpleadosAttritionPCA

array([[-0.7181288 , -0.20869778,  0.4300091 , ...,  0.51567049,
         0.15587226, -0.08216878],
       [-0.69951184, -0.00828653,  0.43467623, ..., -0.18100694,
        -0.10185978,  0.040895  ],
       [ 1.02579702,  0.37296969,  0.58993926, ..., -0.20166288,
         0.31308701, -0.55275751],
       ...,
       [-0.7181288 , -0.20869778,  0.4300091 , ...,  0.51567049,
         0.15587226, -0.08216878],
       [-0.15167055,  0.4857982 , -0.72603349, ..., -0.06305157,
         0.09705965, -0.07475968],
       [-0.0892995 , -0.24621798, -0.27826361, ..., -0.18282335,
        -0.13217042,  0.00668587]])

In [ ]:
#  Varianza acumulada
varianza_acum = np.cumsum(pca.explained_variance_ratio_) # % de la varianza de cada componente se va acumulando

# Número mínimo de componentes que explican al menos el 80%
n_componentes = (varianza_acum >= 0.80).argmax() + 1 #1 por los componentes que se cuentan desde 1
print("Número de componentes necesarios:", n_componentes)

# Agregar columnas C0, C1, ... al DataFrame final
for i in range(n_componentes):
    EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(**{f"C{i}": EmpleadosAttritionPCA[:, i]})

print(EmpleadosAttritionFinal.head())

Número de componentes necesarios: 6
   Attrition  BusinessTravel_Non-Travel  EducationField_Technical Degree  \
0        1.0                        0.0                              0.0
1        1.0                        0.0                              0.0
2        0.0                        0.0                              0.0
3        1.0                        0.0                              0.0
4        0.0                        0.0                              0.0

   JobRole_Healthcare Representative  JobRole_Laboratory Technician  \
0                                0.0                            0.0
1                                0.0                            0.0
2                                0.0                            0.0
3                                1.0                            0.0
4                                0.0                            0.0

   JobRole_Research Director  JobRole_Sales Representative  \
0                        1.0                           0.0
1                        0.0                           0.0
2                        0.0                           1.0
3                        0.0                           0.0
4                        0.0                           0.0

   MaritalStatus_Divorced  MaritalStatus_Single        C0        C1        C2  \
0                     1.0                   0.0 -0.718129 -0.208698  0.430009
1                     1.0                   0.0 -0.699512 -0.008287  0.434676
2                     0.0                   1.0  1.025797  0.372970  0.589939
3                     0.0                   1.0  0.601736 -0.444313  0.206079
4                     0.0                   0.0  0.187644  0.311950 -0.010616

         C3        C4        C5
0  0.093151 -0.661400 -0.277782
1  0.042976 -0.055094 -0.128072
2 -0.434889 -0.079711  0.187925
3  0.244849  0.782882 -0.282137
4 -0.764661 -0.077266  0.202015

In [72]:
EmpleadosAttritionFinal.to_csv('EmpleadosAttritionFinal.csv')